### ISSUE TITLE
question 6...

### ISSUE THREAD

**Issue by amdiamond107** [learn-co-curriculum/phase-1-quiz-javascript-fundamentals#2]
the 6 blank spots in front of "keyword" on question 6 threw me off, and not sure if the intent was to do so, but if so, I'd recommend just putting the proper amount of 3 blank spots instead of 6. I probably would've submitted "let" for question 6 on my first attempt in that instance...

## Issue Subtype

- [ ] Master branch code
- [ ] Solution branch code
- [ ] Code tests
- [ ] Layout/rendering issue
- [ ] Instructions unclear
- [ ] Other (explain below)

### Source

```

```

## What OS Are You Using?

- [ ] OS X
- [ ] Windows
- [ ] WSL
- [ ] Linux
- [ ] Saturn Cloud from Canvas

**Comment by lizbur10** [comment]
Hi @amdiamond107! I'm so sorry to hear that this threw you off! I apologize if the way the blank appeared on your screen is misleading - we aren't always able to control exactly how it renders on different systems. 

The size of the blank is not intended to be related to the length of the answer. Since all of the quizzes in the curriculum are set up that way, I need to leave the question as is for consistency. 

Sorry for the inconvenience and thanks for contributing to the Flatiron School curriculum 💙

**Comment by amdiamond107** [comment]
If you must leave as is, then you absolutely should include a disclaimer
because I wasted 45 mins of my night trying to figure it out under the
guise of it having to be a 6-letter word due to the rendering of 6 blank
character lines instead of 3 or instead of just a straight line like so:
_________

I will also note that there are a litany of other very poorly
constructed/worded lessons and examples shown within canvas to the extent
that a beginner like me should not be challenged with on top of learning
the code itself.

I really hope for the sake of future students in the long-term, if not for
my own sake in the near term, that a seasoned copywriter/editor is brought
in to review the lesson plans and to make the necessary changes so that the
material can be digested and retained more efficiently, and so that good
habits can be honed in the early going of this program. Right now, I'm
feeling like I'm developing poor coding habits as a result of these issues.


Andrew Diamond
c: 917-533-5482
<https://www.linkedin.com/in/andrew-m-diamond/>
